name: Update README2

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    steps:
           - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

