name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"  # Ejecuta cada 12 horas
  workflow_dispatch:         # Permite ejecución manual desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clona el repositorio

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
