name: Update README2

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    steps:
      - name: Checkout repository
        - uses: Readme-Workflows/recent-activity@v2.4.1
      - name: Update README with recent activity
        uses: cospino097/cospino097@gmail.com
